# permissions for end users to edit minecraftserverautoscalers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: minecraftserverautoscaler-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: strela
    app.kubernetes.io/part-of: strela
    app.kubernetes.io/managed-by: kustomize
  name: minecraftserverautoscaler-editor-role
rules:
- apiGroups:
  - strela.dev
  resources:
  - minecraftserverautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - strela.dev
  resources:
  - minecraftserverautoscalers/status
  verbs:
  - get
