# permissions for end users to view minecraftservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: minecraftserver-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: strela
    app.kubernetes.io/part-of: strela
    app.kubernetes.io/managed-by: kustomize
  name: minecraftserver-viewer-role
rules:
- apiGroups:
  - strela.dev
  resources:
  - minecraftservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - strela.dev
  resources:
  - minecraftservers/status
  verbs:
  - get
