---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - strela.dev
  resources:
  - minecraftdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - strela.dev
  resources:
  - minecraftdeployments/finalizers
  verbs:
  - update
- apiGroups:
  - strela.dev
  resources:
  - minecraftdeployments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - strela.dev
  resources:
  - minecraftserverautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - strela.dev
  resources:
  - minecraftserverautoscalers/finalizers
  verbs:
  - update
- apiGroups:
  - strela.dev
  resources:
  - minecraftserverautoscalers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - strela.dev
  resources:
  - minecraftservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - strela.dev
  resources:
  - minecraftservers/finalizers
  verbs:
  - update
- apiGroups:
  - strela.dev
  resources:
  - minecraftservers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - strela.dev
  resources:
  - minecraftserversets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - strela.dev
  resources:
  - minecraftserversets/finalizers
  verbs:
  - update
- apiGroups:
  - strela.dev
  resources:
  - minecraftserversets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - strela.dev
  resources:
  - minecraftstatefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - strela.dev
  resources:
  - minecraftstatefulsets/finalizers
  verbs:
  - update
- apiGroups:
  - strela.dev
  resources:
  - minecraftstatefulsets/status
  verbs:
  - get
  - patch
  - update
