apiVersion: strela.dev/v1
kind: MinecraftServerAutoscaler
metadata:
  labels:
    app.kubernetes.io/name: minecraftserverautoscaler
    app.kubernetes.io/instance: minecraftserverautoscaler-sample
    app.kubernetes.io/part-of: strela
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: strela
  name: minecraftserverautoscaler-sample
spec:
  targetDeployment: minecraftdeployment-sample
  type: SLOT
  desiredPlayers: 10
  minScalePause: 1
