apiVersion: strela.dev/v1
kind: MinecraftServerSet
metadata:
  labels:
    app.kubernetes.io/name: minecraftserverset
    app.kubernetes.io/instance: minecraftserverset-sample
    app.kubernetes.io/part-of: strela
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: strela
  name: minecraftserverset-sample
spec:
  replicas: 1
  template:
    spec:
      configDir: "/server"
      configurationMode: "VELOCITY"
      template:
        spec:
          containers:
            - image: ghcr.io/strela-dev/docker-minecraft-proxy:main
              imagePullPolicy: Always
              name: proxy
              tty: true
              stdin: true
              ports:
                - containerPort: 25577
                  name: main
              env:
                - name: "TYPE"
                  value: "VELOCITY"
