apiVersion: strela.dev/v1
kind: MinecraftServerSet
metadata:
  labels:
    app.kubernetes.io/name: minecraftserverset
    app.kubernetes.io/instance: minecraftserverset-sample
    app.kubernetes.io/part-of: strela
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: strela
  name: minecraftserverset-sample
spec:
  # TODO(user): Add fields here
