apiVersion: strela.dev/v1
kind: MinecraftDeployment
metadata:
  labels:
    app.kubernetes.io/name: minecraftdeployment
    app.kubernetes.io/instance: minecraftdeployment-sample
    app.kubernetes.io/part-of: strela
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: strela
    cloud-group: minecraftdeployment-sample
  name: minecraftdeployment-sample
spec:
  replicas: 1
  type: PROXY
  template:
    spec:
      template:
        spec:
          containers:
            - image: ghcr.io/strela-dev/docker-minecraft-proxy:main
              imagePullPolicy: Always
              name: proxy
              tty: true
              stdin: true
              ports:
                - containerPort: 25577
                  name: main
              env:
                - name: "TYPE"
                  value: "VELOCITY"
---
apiVersion: v1
kind: Service
metadata:
  name: proxy
spec:
  type: NodePort
  selector:
    cloud-group: minecraftdeployment-sample
  ports:
    - port: 25577
      nodePort: 30065