apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "strela.fullname" . }}-manager-role
  labels:
  {{- include "strela.labels" . | nindent 4 }}
rules:
- apiGroups:
  - strela.dev
  resources:
  - minecraftdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - strela.dev
  resources:
  - minecraftdeployments/finalizers
  verbs:
  - update
- apiGroups:
  - strela.dev
  resources:
  - minecraftdeployments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - strela.dev
  resources:
  - minecraftserverautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - strela.dev
  resources:
  - minecraftserverautoscalers/finalizers
  verbs:
  - update
- apiGroups:
  - strela.dev
  resources:
  - minecraftserverautoscalers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - strela.dev
  resources:
  - minecraftservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - strela.dev
  resources:
  - minecraftservers/finalizers
  verbs:
  - update
- apiGroups:
  - strela.dev
  resources:
  - minecraftservers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - strela.dev
  resources:
  - minecraftserversets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - strela.dev
  resources:
  - minecraftserversets/finalizers
  verbs:
  - update
- apiGroups:
  - strela.dev
  resources:
  - minecraftserversets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - strela.dev
  resources:
  - minecraftstatefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - strela.dev
  resources:
  - minecraftstatefulsets/finalizers
  verbs:
  - update
- apiGroups:
  - strela.dev
  resources:
  - minecraftstatefulsets/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "strela.fullname" . }}-manager-rolebinding
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: strela
    app.kubernetes.io/part-of: strela
  {{- include "strela.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "strela.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "strela.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'