apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "strela.fullname" . }}-controller-manager
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: strela
    app.kubernetes.io/part-of: strela
  {{- include "strela.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.controllerManager.serviceAccount.annotations | nindent 4 }}