# Reference: https://github.com/helm/chart-releaser-action
name: Helm Chart Publish
on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  publish:
    permissions:
      contents: write  # for helm/chart-releaser-action to push chart release and create a release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v3

      #- name: Add dependency chart repos
      #  run: |
      #    helm repo add dandydeveloper https://dandydeveloper.github.io/charts/

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        with:
          charts_dir: charts
        env:
          CR_TOKEN: "${{ secrets.CR_PAT }}"